zip:
  targetFolder: ./dist
  outName: date
openApi:
  requestLibPath: import {request} from '../utils/request'
  schemaPath: /Users/wangzhongjie/Desktop/github/go-gin-api/docs/swagger.json
  serversPath: ./
upload:
  serverType: linux
  port: 22
  host: ''
  userName: ''
  password: ''
  targetDir: ''
  localDir: dist
